### ISSUE TITLE
Create Issue Form Should Have Alternate Submit Behaviors

### ISSUE THREAD

**Issue by EthanCloin** [EthanCloin/issue-tracker-capstone#21]
# Summary
`CreateIssuePage.tsx`
Intended behavior is for user to be able to stay on the page if the
select the "Create and Add Another" button, but be redirected to Home
when "Create" is selected. 

## Previous Attempt
I was looking into accessing the `.submitter` property on the SubmitEvent. 
This was problematic since it seemed like TS was expecting a FormEvent<HTMLElement> instead.

## Suggestion

I think a simpler and cleaner strategy will be to add a state variable `shouldGoHome`. 
This variable would also be useful for the "Discard" button. 

Also remove the mess from the previous attempt ... 🤢

**Comment by frenbren** [comment]
Have you tried useNavigate()? https://reactrouter.com/en/main/hooks/use-navigate

**Comment by EthanCloin** [comment]
> Have you tried useNavigate()? https://reactrouter.com/en/main/hooks/use-navigate

yes this will definitely be the right hook to perform the actual navigation! the main issue here was more how to distinguish between which submit button was pressed. now it just needs implemented and battle-tested.

**Comment by EthanCloin** [comment]
Implemented in commit ff45404fe91a47769643d4a3e20220d4236e9ee1
