### ISSUE TITLE
Navbar UX Improvement

### ISSUE THREAD

**Issue by EthanCloin** [EthanCloin/issue-tracker-capstone#24]
# Summary
Navbar should update to include a Back Arrow on the top left corner when user is in either Add or Detail pages. Clicking the 'Issue Tracker' text already routes back to home, but the arrow will make it more clearly an option.

**Comment by khangb1910652** [comment]
I want to participate in troubleshooting Navbar UX Improvements

**Comment by nguyenduykhang444** [comment]
I helped you to solve the issue Navbar UX Improvement. You can see it in the pull request section.

**Comment by EthanCloin** [comment]
Thanks for the contribution! Approved and merged in PR #28
